### ISSUE TITLE
Excuse me, I would like to ask me about an error I encountered while running the code

### ISSUE THREAD

**Issue by cyx9898010** [Qznan/SpanKL#2]
When I run python
train_clner.py
>       --gpu 0 
>       --m spankl 
>       --corpus onto 
>       --setup split 
>       --perm perm0
At the command line, he reported an error 401 Client Error: Unauthorized for url: https://huggingface.co/huggingface_model_resource/bert-base-cased/resolve/main/config.json.
I don't know how to fix this. Can you help me solve this problem? Thank you.

**Comment by Qznan** [comment]
Hi, You may need to download the pre-trained models from HuggingFace, [bert-large-cased](https://huggingface.co/bert-large-cased/tree/main) or [bert-base-cased](https://huggingface.co/bert-base-cased/tree/main) into `huggingface_model_resource/`, based on your choice as refered in the code:
```
# Line:1052, File:train_clner.py
args.bert_model_dir = ['huggingface_model_resource/bert-base-cased', 'huggingface_model_resource/bert-large-cased'][1]
```
Alternatively, you can directly set
```
args.bert_model_dir = 'bert-large-cased'
```
to utilize the automatically model downloading service by HuggingFace from the internet.

**Comment by cyx9898010** [comment]
thx. I have resoled it.
