### ISSUE TITLE
model_ckpt/fewnerd-0-2023-03-03_13-27-48-1406-spankl_split_perm0/overview_metric.json'

### ISSUE THREAD

**Issue by subhendu98IN** [Qznan/SpanKL#3]
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-10-7af3f4341cd5>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 model_ckpt = 'fewnerd-0-2023-03-03_13-27-48-1406-spankl_split_perm0'
----> 5 metrics_json = utils.load_json(f'model_ckpt/{model_ckpt}/overview_metric.json')
      6 test_metric = metrics_json['test_metric']
      7 filter_test_metric = metrics_json['filter_test_metric'] if 'filter_test_metric' in metrics_json else None

[/content/drive/MyDrive/SpanKL/datautils.py](https://localhost:8080/#) in load_json(json_file)
    141 
    142 def load_json(json_file):
--> 143     with open(json_file, 'r', encoding='U8') as f:
    144         json_data = json.load(f)
    145     return json_data

FileNotFoundError: [Errno 2] No such file or directory: 'model_ckpt/fewnerd-0-2023-03-03_13-27-48-1406-spankl_split_perm0/overview_metric.json'

**Comment by subhendu98IN** [comment]
The above issue solved. Now getting this issue.

SystemExit                                Traceback (most recent call last)
Cell In[5], line 1052
   1050 # A experimental setting to verify the Standard Supervised Full Data performance. != cl or non_cl
   1051 parser.add_argument('--all_tasks', default=False, type=utils.str2bool)  # all tasks (Standard Supervised Full Data)
-> 1052 args = parser.parse_args()
   1054 #args.bert_model_dir = ['huggingface_model_resource/bert-base-cased', 'huggingface_model_resource/bert-large-cased'][1]
   1055 args.bert_model_dir = 'bert-large-cased'

File /opt/conda/lib/python3.10/argparse.py:1829, in ArgumentParser.parse_args(self, args, namespace)
   1827 if argv:
   1828     msg = _('unrecognized arguments: %s')
-> 1829     self.error(msg % ' '.join(argv))
   1830 return args

File /opt/conda/lib/python3.10/argparse.py:2587, in ArgumentParser.error(self, message)
   2585 self.print_usage(_sys.stderr)
   2586 args = {'prog': self.prog, 'message': message}
-> 2587 self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

File /opt/conda/lib/python3.10/argparse.py:2574, in ArgumentParser.exit(self, status, message)
   2572 if message:
   2573     self._print_message(message, _sys.stderr)
-> 2574 _sys.exit(status)

SystemExit: 2

**Comment by Qznan** [comment]
It seems like some cmd args cannot been successfully parsed, can you post the command you want to run?
