### ISSUE TITLE
General question about the model

### ISSUE THREAD

**Issue by zccarli** [Qznan/SpanKL#4]
I am a bit confused about how to use a customized dataset. I have a NER dataset that only contains annotated label 'ORG'. Do I need to train the model with another dataset contains multiple labels(e.g., ORG, PER, like a OntoNotes-5.0 English dataset), and train again using my own NER dataset? 

Actually I would like to enhance the performance for lablelling 'ORG' when new data comes in sequentially. But I don't know how to deal with it.

**Comment by Qznan** [comment]
If you have a customized dataset without new entity types beyond the base model (e.g., a model training with OntoNotes-5.0), you can simple use the code to conduct incremental training by replacing some step's dataset by your own dataset, and modifying some of the training code necessary to suit your production scenario.

**Comment by zccarli** [comment]
Thank you for your time and reply. I saw 6 tasks were conducted in a specific permutation by using OntoNotes dataset which includes training for the label 'ORG'. I am wondering what if I add another task (e.g., task 7) with only annotation for 'ORG', will it act like an incremental training? Is 'continual learning' only prepared for learning new entities?

**Comment by Qznan** [comment]
Sounds like the domain-incremental learning. i.e., new samples but the same class. But you can also try in the regime of this incremental learning code to figure out what the performance looks like~
