### ISSUE TITLE
关于超参数

### ISSUE THREAD

**Issue by tianylin98** [Qznan/SpanKL#6]
请问`train_clner.py`脚本中的[这几行](https://github.com/Qznan/SpanKL/blob/64f747dc3630c54c71dc68aab1c02aa97831b8a7/train_clner.py#L1054C5-L1061C28)
```python
    if args.corpus == 'onto':
        args.perm_ids = onto_sorted_ids_dct[args.perm]
        args.batch_size = 32
        args.num_epochs = 2
    if args.corpus == 'fewnerd':
        args.perm_ids = fewnerd_sorted_ids_dct[args.perm]
        args.batch_size = 24
        args.num_epochs = 2
```
就是论文中用到的超参数吗？num_epochs似乎和文章对不上...

**Comment by Qznan** [comment]
您好，感谢指出~
原始上传的代码设置为ontonote中epochs=10，fewnerd中epochs=5。与论文保持一致。
后面在一个commit的时候为了快速测试代码临时修改了epoches，忘了改回去就commit了😂。现已更新
